config:
  path: results/
  runs: 1
  nshots: 4000
  benchmarks:
    - name: PhaseCodeBenchmark
      nqbits: 3
      rounds: 3
      cut: false
      
      frags:
        - backend: FakeTorontoV2
    - name: GHZBenchmark
      nqbits: 3
      rounds:
      cut: false
      frags:
        - backend: FakeTorontoV2