config:
  path: results/
  nshots: 8192
  static: false
  benchmarks:
    - name: BitCodeBenchmark
      nqbits: 4
      rounds: 2
      nlayers:
      time_step:
      total_time:
      inital_state:
      cut: false
      frags:
        - backend: FakeTorontoV2