config:
  path: results/
  nshots: 8192
  nruns: 7
  static: false
  benchmarks:
    - name: HamiltonianSimulationBenchmark
      nqbits: 7
      rounds:
      nlayers:
      time_step:
      total_time:
      initial_state:
      cut: false
      frags:
        - backend: FakeSingaporeV2